#! /bin/sh

sxhkd &

# wallpaper
hsetroot -center /home/pramji/Pictures/montage.jpg

bspc monitor DP-4 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

# spacing/gaps
bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config auto_cancel          true

# global
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true

# colors
bspc config focused_border_color "#47575f"
bspc config normal_border_color "#526562"
bspc config presel_feedback_color "#804f4e"

bspc rule -a URxvt:pulsemixer state=floating

$HOME/.config/polybar/launch.sh
