#! /bin/sh

# startup applications
sxhkd &
# compton &
dropbox &
solaar &
synergy &
wmname LG3D
jetbrains-toolbox &

# wallpaper
hsetroot -center '/home/pramji/Pictures/montage.jpg'

bspc monitor DP-4 -d I II III IV V VI VII VIII
bspc monitor HDMI-0 -d IX X

# spacing/gaps
bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config auto_cancel          true

# global
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true

# colors
bspc config focused_border_color "#FF3334"
bspc config normal_border_color "#81a2be"
bspc config presel_feedback_color "#81a2be"

bspc config external_rules_command '/home/pramji/.config/bspwm/windowclassname.sh'

# bspc config wm_name LG3D

bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:calculator state=floating
bspc rule -a Gimp desktop=^4 follow=on state=floating
bspc rule -a Gnome-mplayer follow=on state=floating
bspc rule -a MPlayer follow=on state=floating
bspc rule -a Evolution desktop=^3 follow=on
bspc rule -a Vmware desktop=^4 follow=on state=floating
bspc rule -a Synergy state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Rv.bin follow=on state=floating
bspc rule -a Solaar:solaar state=floating
bspc rule -a Shotgun:shotgun follow=on state=floating

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

$HOME/.config/polybar/launch.sh
# $HOME/.config/bspwm/floatingwindows.sh &
