[window]
  padding = { x = 8, y = 8 }

[font]
  size = 12.0
  normal = { family = "Hack Nerd Font Mono" }
  bold = { family = "Hack Nerd Font Mono" }
  italic = { family = "Hack Nerd Font Mono" }
  bold_italic = { family = "Hack Nerd Font Mono" }

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
  background = '#1a1b26'
  foreground = '#c0caf5'

#[colors.cursor]
#  cursor = '#c0caf5'
#  text = '#1a1b26'

# Normal colors
[colors.normal]
  black = '#15161e'
  red = '#f7768e'
  green = '#9ece6a'
  yellow = '#e0af68'
  blue = '#7aa2f7'
  magenta = '#bb9af7'
  cyan = '#7dcfff'
  white = '#a9b1d6'

# Bright colors
[colors.bright]
  black = '#414868'
  red = '#ff899d'
  green = '#9fe044'
  yellow = '#faba4a'
  blue = '#8db0ff'
  magenta = '#c7a9ff'
  cyan = '#a4daff'
  white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
  index = 16
  color = '#ff9e64'

[[colors.indexed_colors]]
  index = 17
  color = '#db4b4b'

[keyboard]
  bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },
    { key = "Right", mods = "Alt", chars = "\u001bF" },
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars =  "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "Key1", mods = "Alt", chars = "\u001b1" },
    { key = "Key2", mods = "Alt", chars = "\u001b2" },
  ]

