[window]
  padding = { x = 8, y = 8 }

[font]
  size = 12.0
  normal = { family = "Source Code Pro" }
  bold = { family = "Source Code Pro" }
  italic = { family = "Source Code Pro" }
  bold_italic = { family = "Source Code Pro" }

[colors.primary]
  background = "0x282c34"
  foreground = "0xbbc2cf"

[colors.normal]
  black = "0x282c34"
  red = "0xff6c6b"
  green = "0x98be65"
  yellow = "0xecbe7b"
  blue = "0x51afef"
  magenta = "0xc678dd"
  cyan = "0x46d9ff"
  white = "0xbbc2cf"

[keyboard]
  bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },
    { key = "Right", mods = "Alt", chars = "\u001bF" },
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars =  "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "Key1", mods = "Alt", chars = "\u001b1" },
    { key = "Key2", mods = "Alt", chars = "\u001b2" },
  ]

